package com.bettercalculator.farming.util;

import lombok.Getter;
import net.runelite.api.ItemID;

@Getter
public enum SeedType
{
	/* ALLOTMENTS */
	POTATO(ItemID.POTATO_SEED, 1),
	ONION(ItemID.ONION_SEED, 5),
	CABBAGE(ItemID.CABBAGE_SEED, 7),
	TOMATO(ItemID.TOMATO_SEED, 12),
	SWEETCORN(ItemID.SWEETCORN_SEED, 20),
	STRAWBERRY(ItemID.STRAWBERRY_SEED, 31),
	WATERMELON(ItemID.WATERMELON_SEED, 47),
	SNAPE_GRASS(ItemID.SNAPE_GRASS_SEED, 61),
	/* FLOWERS */
	MARIGOLD(ItemID.MARIGOLD_SEED, 2),
	ROSEMARY(ItemID.ROSEMARY_SEED, 11),
	NASTURTIUM(ItemID.NASTURTIUM_SEED, 24),
	WOAD(ItemID.WOAD_SEED, 25),
	LIMPWURT(ItemID.LIMPWURT_SEED, 26),
	WHITE_LILY(ItemID.WHITE_LILY_SEED, 58),
	/* HERBS */
	GUAM(ItemID.GUAM_SEED, 9),
	MARRENTILL(ItemID.MARRENTILL_SEED, 14),
	TARROMIN(ItemID.TARROMIN_SEED, 19),
	HARRALANDER(ItemID.HARRALANDER_SEED, 26),
	GOUT_TUBER(ItemID.GOUT_TUBER, 29),
	RANARR(ItemID.RANARR_SEED, 32),
	TOADFLAX(ItemID.TOADFLAX_SEED, 38),
	IRIT(ItemID.IRIT_SEED, 44),
	AVANTOE(ItemID.AVANTOE_SEED, 50),
	KWUARM(ItemID.KWUARM_SEED, 56),
	SNAPDRAGON(ItemID.SNAPDRAGON_SEED, 62),
	CADANTINE(ItemID.CADANTINE_SEED, 67),
	LANTADYME(ItemID.LANTADYME_SEED, 73),
	DWARF_WEED(ItemID.DWARF_WEED_SEED, 79),
	TORSTOL(ItemID.TORSTOL_SEED, 85),
	/* HOPS */
	BARLEY(ItemID.BARLEY_SEED, 3),
	HAMMERSTONE(ItemID.HAMMERSTONE_SEED, 4),
	ASGARNIAN(ItemID.ASGARNIAN_SEED, 8),
	JUTE(ItemID.JUTE_SEED, 13),
	YANILLIAN(ItemID.YANILLIAN_SEED, 16),
	KRANDORIAN(ItemID.KRANDORIAN_SEED, 21),
	WILDBLOOD(ItemID.WILDBLOOD_SEED, 28),
	/* BUSHES */
	REDBERRY(ItemID.REDBERRY_SEED, 10),
	CADAVABERRY(ItemID.CADAVABERRY_SEED, 22),
	DWELLBERRY(ItemID.DWELLBERRY_SEED, 36),
	JANGERBERRY(ItemID.JANGERBERRY_SEED, 48),
	WHITEBERRY(ItemID.WHITEBERRY_SEED, 59),
	POISON_IVY_BERRY(ItemID.POISON_IVY_SEED, 70),
	/* TREES */
	ACORN(ItemID.ACORN, 15),
	WILLOW(ItemID.WILLOW_SAPLING, 30),
	MAPLE(ItemID.MAPLE_SAPLING, 45),
	YEW(ItemID.YEW_SAPLING, 60),
	MAGIC(ItemID.MAGIC_SAPLING, 75),
	/* FRUIT TREE SEEDS */
	APPLE(ItemID.APPLE_SAPLING, 27),
	BANANA(ItemID.BANANA_SAPLING, 33),
	ORANGE(ItemID.ORANGE_SAPLING, 39),
	CURRY(ItemID.CURRY_SAPLING, 42),
	PINEAPPLE(ItemID.PINEAPPLE_SAPLING, 51),
	PAPAYA(ItemID.PAPAYA_SAPLING, 57),
	PALM_TREE(ItemID.PALM_SAPLING, 68),
	DRAGONFRUIT(ItemID.DRAGONFRUIT_SAPLING, 81),
	/* SPECIAL */
	GIANT_SEAWEED(ItemID.SEAWEED_SPORE, 23),
	GRAPES(ItemID.GRAPE_SEED, 36),
	MUSHROOM(ItemID.MUSHROOM_SPORE, 53),
	BELLADONNA(ItemID.BELLADONNA_SEED, 63),
	HESPORI(ItemID.HESPORI_SEED, 65),
	/* ANIMA */
	KRONOS(ItemID.KRONOS_SEED, 76),
	IASOR(ItemID.IASOR_SEED, 76),
	ATTAS(ItemID.ATTAS_SEED, 76),
	/* SPECIAL TREE SEEDS */
	TEAK(ItemID.TEAK_SAPLING, 35),
	MAHOGANY(ItemID.MAHOGANY_SAPLING, 55),
	CALQUAT_TREE(ItemID.CALQUAT_SAPLING, 72),
	CRYSTAL_TREE(ItemID.CRYSTAL_SAPLING, 74),
	SPIRIT_TREE(ItemID.SPIRIT_SAPLING, 83),
	CELASTRUS(ItemID.CELASTRUS_SAPLING, 85),
	REDWOOD(ItemID.REDWOOD_SAPLING, 90),
	/* CACTI */
	CACTUS(ItemID.CACTUS_SEED, 55),
	POTATO_CACTUS(ItemID.POTATO_CACTUS_SEED, 64),
	;


	private final int itemID;
	private final int requiredFarmingLevel;
	SeedType(int itemID, int requiredFarmingLevel)
	{
		this.itemID = itemID;
		this.requiredFarmingLevel = requiredFarmingLevel;
	}
}
